name: Go
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: ouzi-dev/commit-status-updater@v1.1.0
       with:
         name: "Coverage"
         status: "error"
         description: "Test coverage: TEST"
