name: Go
on:
  push:
    branches: [ main, CoverageActionTest]
  pull_request_target:
    branches: [ main, CoverageActionTest]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        name: "Coverage"
        ignoreForks: false
        status: "error"
        description: "Test coverage: TEST"

    - uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        name: "Coverage"
        ignoreForks: false
        status: "error"
        description: "Test 2coverage: TEST"

    - uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        name: "Coverage"
        ignoreForks: false
        status: "error"
        description: "Test 2coverage: TEST"
