name: "KinD"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing on KinD
        run: |
          export GO111MODULE=on
          export PATH=$PATH:$(go env GOPATH)/bin
          kubectl cluster-info
          kubectl get pods -n kube-system
          make generate
          make install
          timeout 1m make run || retVal=$?
          if [ $retVal -ne 124 ]; then
            echo "Make run failed"; exit 1
          fi

      - name: Integration tests
        run: |
          timeout 10m ./tests/bats/bin/bats --verbose-run tests/registration.bats
